name: Scanning for secrets in commits
on:
  pull_request:
    branches:
      - main
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run TruffleHog Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --no-verification
    - name: Parse TruffleHog Output for Annotations
      if: always() # Ensure this step runs even if the previous step fails
      run: |
        # Check if annotations exist in the job logs
        echo "Scanning job logs for annotations:"
        # Retrieve annotations from GitHub Actions job logs
        annotations=$(grep "::" $GITHUB_WORKSPACE | grep "error\|warning\|notice" || true)
        if [ -n "$annotations" ]; then
          echo "Annotations Found:"
          echo "$annotations"
        else
          echo "No annotations found in the logs."
        fi
     
