name: Scanning for secrets in commits
on:
  pull_request:
    branches:
      - main
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run TruffleHog Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --no-verification

    - name: Fetch Check Run ID
      if: always()
      id: fetch_check_run_id
      run: |
        # Fetch the workflow run ID
        workflow_run_id=${{ github.run_id }}

        # Fetch the check runs for this workflow run
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_run_id/check-runs")

        # Parse the first check run ID
        check_run_id=$(echo "$response" | jq -r '.check_runs[0].id')        
        echo "Check Run ID: $check_run_id"

    
     
